"""Create Database

Revision ID: 4ceed0ed6189
Revises: 
Create Date: 2024-11-01 12:41:39.821957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceed0ed6189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furniture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('TABLE', 'CHAIR', 'BED', 'CLOSET', 'DRAWER', name='categoryenum'), nullable=False),
    sa.Column('material', sa.Enum('WOOD', 'METAL', 'PLASTIC', name='materialenum'), nullable=False),
    sa.Column('manufacturer', sa.Enum('AZERBAIJAN', 'UNITED_STATES', 'RUSSIAN_FEDERATION', 'UKRAINE', 'UNITED_KINGDOM', 'BELARUS', 'ITALY', 'GERMANY', 'IRELAND', name='countryenum'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furniture_fullname'), 'furniture', ['fullname'], unique=False)
    op.create_index(op.f('ix_furniture_id'), 'furniture', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_furniture_id'), table_name='furniture')
    op.drop_index(op.f('ix_furniture_fullname'), table_name='furniture')
    op.drop_table('furniture')
    # ### end Alembic commands ###
