"""User

Revision ID: a615068709f4
Revises: ceb6cd06129a
Create Date: 2024-11-09 19:47:28.763742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a615068709f4'
down_revision: Union[str, None] = 'ceb6cd06129a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_furniture_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'furniture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('furniture_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_furniture_id_fkey', 'user', 'furniture', ['furniture_id'], ['id'])
    # ### end Alembic commands ###
