"""User

Revision ID: ceb6cd06129a
Revises: c383660ef368
Create Date: 2024-11-09 19:11:43.815137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb6cd06129a'
down_revision: Union[str, None] = 'c383660ef368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'furniture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'furniture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
